### PR TITLE
We should specify when release must occur by

### PR DESCRIPTION
**Pull request by cgreene**
Motivation: Currently the timing of the sharing of outputs is not well defined. We should commit to share at or before the conclusion of the funding period.

### CODE REVIEW

**Comment by dhimmel** [comment]
We currently mandate release prior to publication:

> Prior to submission of project manuscripts to a journal, all related outputs will be made publicly available under the aforementioned licensing guidelines and deposited to persistent archives.

@cgreene has identified an issue where unpublished outputs don't have a release deadline. He suggests the bolded modification:

> All outputs from this project — including code, data, figures, documentation, and manuscripts — will be made publicly available under an open license **on or before the date at which the award ends**.

This isn't a problem for those who do realtime openness. However, we intentionally did not mandate realtime openness since many users may be unwilling to make that commitment. Let's imagine a situation where the grant funds a discovery that you don't want to publicize until your preprint is complete. However, the grant funding elapses and you're still working on wrapping up the project. Therefore, I think a one or two year grace period makes sense.

@cgreene, I can't believe I'm advocating for a delay in openness, but if you have a valid reason to not be doing realtime openness, I think grant expiration is a bit premature. What do you think?

**Review by dhimmel — APPROVED** [review]

**Comment by dhimmel** [comment]
@cgreene I think a squash commit is the way to go here -- now we have three commits for a single sentence change. Mind if I rewrite master?

**Comment by cgreene** [comment]
Ahh - bummer - yea - go for it!

**Comment by dhimmel** [comment]
Okay squashed into https://github.com/lab-carpentry/blueprint-resourcesharing/commit/8a41caec57fe63dfcfd5db8213e10551306c1725.

**Comment by cgreene** [comment]
Thanks @dhimmel!

**Pull request merged**
